#include "ros/ros.h"
#include "server_client/SrvTutorial.h" // autogenerated after build
#include <cstdlib> // library for using atoll function which converts str to int

int main(int argc, char **argv){
    ros::init(argc, argv, "client");
    if(argc != 3){
        ROS_INFO(" need two numbers seprated by space for arguments");
        return 1;
    }

    ros::NodeHandle nh;

    ros::ServiceClient service_client = 
    nh.serviceClient<server_client::SrvTutorial>("ros_tutorial_srv");

    // declare a service that uses SrvTutorial
    server_client::SrvTutorial srv;

    srv.request.a = atoll(argv[1]);
    srv.request.b = atoll(argv[2]);

   // Request the service, and if the request is accepted, display the response value
if (service_client.call(srv)){
    ROS_INFO("send srv, srv.Request.a and b: %ld, %ld", (long int)srv.request.a, (long int)srv.request.b);
    ROS_INFO("receive srv, srv.Response.result: %ld", (long int)srv.response.result);
} else {
    ROS_ERROR("Failed to call service ros_tutorial_srv");
    return 1;
}
return 0;



}