#include "ros/ros.h"
#include "server_client/SrvTutorial.h" // autogenerated after build

// handle request
bool calculation(server_client::SrvTutorial::Request &req, 
                server_client::SrvTutorial::Response &resp){
    resp.result = req.a + req.b;

    ROS_INFO("request: x=%ld, y=%ld", (long int)req.a, (long int)req.b);
    ROS_INFO("sending back response: %ld", (long int)resp.result);
    return true;
}

int main(int argc, char **argv){
    ros::init(argc, argv, "server");
    ros::NodeHandle nh;

      ros::ServiceServer service_server = 
      nh.advertiseService("ros_tutorial_srv", calculation);
    ROS_INFO("Srv server is ready yall");
    ros::spin();// wait for service request

    return 0;
}